mod central_pubkey;
mod command_auth;
mod config;
mod encryption;
mod error;
mod identity;
mod obfuscate;
mod onvif_auth;
mod paths;
mod pinned_cert;
mod source;
mod storage;
mod tls_cert;

pub use central_pubkey::CentralPubkeyConfig;
pub use command_auth::{sign_command, verify_command, CommandAuthError};
pub use config::{AdaptiveConfig, AdaptivePriority, CentralConfig, RecordingConfig, RemoteConfig};
pub use encryption::EncryptionConfig;
pub use error::ConfigError;
pub use identity::IdentityConfig;
pub use onvif_auth::{generate_random_password, OnvifAuthConfig};
pub use paths::{central_config_path, config_dir, ensure_config_dir, remote_config_path, write_secure};
pub use pinned_cert::PinnedCertConfig;
pub use source::{OnvifConfig, RtspConfig, SourceConfig};
pub use storage::StorageConfig;
pub use tls_cert::TlsCertConfig;
